version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
